image: docker:latest
services:
  - docker:dind

stages:
  - deploy

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=./.m2/repository -Dnexus.url=$NEXUS_URL -Dnexus.login=$NEXUS_USERNAME -Dnexus.pwd=$NEXUS_PASSWORD"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version"
  CONTAINER_TEST_IMAGE: $CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_PROJECT_PATH:latest

cache:
  paths:
    - ./.m2/repository
  # keep cache across branch
  key: "$CI_BUILD_REF_NAME"

maven-deploy-central:
  stage: deploy
  image: maven:3-jdk-8
  before_script:
    - gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys AB4649ED8B0734E701EC2BD95B7084F542CA29FA;
    - gpg --export --armor AB4649ED8B0734E701EC2BD95B7084F542CA29FA | sudo apt-key add -
    - echo "pinentry-mode loopback" > /root/.gnupg/gpg.conf;
    - echo -e $GPG_PRIVATE_KEY | gpg --batch --import
  script:
    - "mvn clean deploy -Pprod,maven-central -Dsonar.host.url=http://sonar.si.cnr.it:9000 -Dnexus.url=$SONATYPE_URL -Dnexus.login=$SONATYPE_USERNAME -Dnexus.pwd=$SONATYPE_PASSWORD -Dnexus.repository.releases=$SONATYPE_REPOSITORY_RELEASES -Dgpg.passphrase=$GPG_PASSPHRASE -DskipTests"
  artifacts:
    paths:
      - cool-jconon-webapp/target/*.war
  only:
    - master
