repository.base.url: http://alfresco-community-szn.test.si.cnr.it/alfresco/
org.apache.chemistry.opencmis.binding.spi.type: browser

user.admin.password: admin
server.context-path: /

mail.smtp.auth: true
mail.smtp.starttls.enable: true
mail.smtp.socketFactory.fallback: false

rrd:
  path: remote-shared,remote,remote-szn
  skipmd5: true

ipa:
  url:
    base: https://www.indicepa.gov.it/public-services/opendata-read-service.php
    amministrazioni: ${ipa.url.base}?dstype=FS&filename=amministrazioni.txt
